const data = {
  last_update: "2025-05-01",
  total_province: 34,
  provinces: [
    {
      provinsi: "Jakarta",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jawa Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jawa Tengah",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jawa Timur",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Banten",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Yogyakarta",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Timur",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Bali",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sumatera Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Riau",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Selatan",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sumatera Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Nusa Tenggara Timur",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Selatan",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sumatera Selatan",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Lampung",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kepulauan Riau",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Bangka Belitung",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Tengah",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Tengah",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Papua",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Aceh",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jambi",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Nusa Tenggara Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Papua Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Bengkulu",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Tenggara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Maluku",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Maluku Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Gorontalo",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
  ],
};

export default data;